# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import inventory_pb2 as inventory__pb2


class InventoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchByID = channel.unary_unary(
                '/inventory.InventoryService/SearchByID',
                request_serializer=inventory__pb2.InventoryRequest.SerializeToString,
                response_deserializer=inventory__pb2.InventoryResponse.FromString,
                )
        self.Search = channel.unary_unary(
                '/inventory.InventoryService/Search',
                request_serializer=inventory__pb2.SearchRequest.SerializeToString,
                response_deserializer=inventory__pb2.InventoryResponse.FromString,
                )
        self.SearchRange = channel.unary_stream(
                '/inventory.InventoryService/SearchRange',
                request_serializer=inventory__pb2.SearchRangeRequest.SerializeToString,
                response_deserializer=inventory__pb2.InventoryResponse.FromString,
                )
        self.GetDistribution = channel.unary_unary(
                '/inventory.InventoryService/GetDistribution',
                request_serializer=inventory__pb2.GetDistributionRequest.SerializeToString,
                response_deserializer=inventory__pb2.GetDistributionResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/inventory.InventoryService/Update',
                request_serializer=inventory__pb2.UpdateRequest.SerializeToString,
                response_deserializer=inventory__pb2.UpdateResponse.FromString,
                )


class InventoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDistribution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchByID': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByID,
                    request_deserializer=inventory__pb2.InventoryRequest.FromString,
                    response_serializer=inventory__pb2.InventoryResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=inventory__pb2.SearchRequest.FromString,
                    response_serializer=inventory__pb2.InventoryResponse.SerializeToString,
            ),
            'SearchRange': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchRange,
                    request_deserializer=inventory__pb2.SearchRangeRequest.FromString,
                    response_serializer=inventory__pb2.InventoryResponse.SerializeToString,
            ),
            'GetDistribution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDistribution,
                    request_deserializer=inventory__pb2.GetDistributionRequest.FromString,
                    response_serializer=inventory__pb2.GetDistributionResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=inventory__pb2.UpdateRequest.FromString,
                    response_serializer=inventory__pb2.UpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.InventoryService/SearchByID',
            inventory__pb2.InventoryRequest.SerializeToString,
            inventory__pb2.InventoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.InventoryService/Search',
            inventory__pb2.SearchRequest.SerializeToString,
            inventory__pb2.InventoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/inventory.InventoryService/SearchRange',
            inventory__pb2.SearchRangeRequest.SerializeToString,
            inventory__pb2.InventoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDistribution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.InventoryService/GetDistribution',
            inventory__pb2.GetDistributionRequest.SerializeToString,
            inventory__pb2.GetDistributionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.InventoryService/Update',
            inventory__pb2.UpdateRequest.SerializeToString,
            inventory__pb2.UpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
